FROM node:16

# Create app directory
WORKDIR /home/openbackhaul/microWaveDeviceGatekeeper

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

#RUN npm install
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 4014

#Command to start the application
CMD [ "node", "index.js" ]